version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: find . -path ./.git -prune -o -print
      - run: dotnet build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build