version: 2

jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          name: List files
          command: find . -path ./.git -prune -o -print
      - run: dotnet build
      - run: dotnet test --no-build circleci-helloworld.test